# Generated by Django 3.2 on 2021-06-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191016_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, choices=[('Massa', 'Massa'), ('Cobertura', 'Cobertura'), ('Recheio', 'Recheio'), ('Tamanho', 'Tamanho'), ('Topping', 'Topping')], max_length=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
